server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    database: ${DB_NAME}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/expense_db
  #    username:
  #    password:
  #    driver-class-name: org.postgresql.Driver
  # === Database (Supabase) ===





  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: use_my_secret_use_my_secret_use_my_secret_use_my_secret_use_my_secret_use_my_secret
  app: 3600000