server:
  port: 8080

spring:
  datasource:
#    url: ${DB_URL}
#    username:  ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/expense_db
      username: amar
      password: amar1234
      driver-class-name: org.postgresql.Driver
  # === Database (Supabase) ===
  security:
   oauth2:
   resourceserver:
   jwt:
   secret-key: use_my_secret_use_my_secret_use_my_secret_use_my_secret_use_my_secret_use_my_secret
   expirationMs: 3600000




  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: use_my_secret_use_my_secret_use_my_secret_use_my_secret_use_my_secret_use_my_secret
  expirationMs: 3600000